#!/usr/bin/env bash

if [[ -n "${BASH_SOURCE[0]:-}" ]]; then
  OPEN_MPLANE_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
else
  OPEN_MPLANE_ROOT="$(pwd)"
fi

export OPEN_MPLANE_ROOT
export OPEN_MPLANE_DEV_PREFIX="${OPEN_MPLANE_DEV_PREFIX:-${OPEN_MPLANE_ROOT}/build/dev/install}"
export OPEN_MPLANE_CLIENT_DEPS="${OPEN_MPLANE_CLIENT_DEPS:-${OPEN_MPLANE_ROOT}/mplane_client/deps/install}"

export PATH="${OPEN_MPLANE_DEV_PREFIX}/bin:${OPEN_MPLANE_DEV_PREFIX}/sbin:${OPEN_MPLANE_CLIENT_DEPS}/bin:${PATH}"
export LD_LIBRARY_PATH="${OPEN_MPLANE_DEV_PREFIX}/lib:${OPEN_MPLANE_CLIENT_DEPS}/lib:${OPEN_MPLANE_CLIENT_DEPS}/lib64:${LD_LIBRARY_PATH:-}"
export PKG_CONFIG_PATH="${OPEN_MPLANE_DEV_PREFIX}/lib/pkgconfig:${OPEN_MPLANE_CLIENT_DEPS}/lib/pkgconfig:${OPEN_MPLANE_CLIENT_DEPS}/lib64/pkgconfig:${PKG_CONFIG_PATH:-}"
export CMAKE_PREFIX_PATH="${OPEN_MPLANE_DEV_PREFIX};${OPEN_MPLANE_CLIENT_DEPS};${CMAKE_PREFIX_PATH:-}"

export LIBYANG_EXTENSIONS_PLUGINS_DIR="${OPEN_MPLANE_CLIENT_DEPS}/lib/libyang1/extensions"
export LIBYANG_USER_TYPES_PLUGINS_DIR="${OPEN_MPLANE_CLIENT_DEPS}/lib/libyang1/user_types"
export SYSREPOCTL_EXECUTABLE="${OPEN_MPLANE_CLIENT_DEPS}/bin/sysrepoctl"
export SYSREPOCFG_EXECUTABLE="${OPEN_MPLANE_CLIENT_DEPS}/bin/sysrepocfg"
